version: '3.1'

services:

  web:
    image: nginx
    volumes:
      - ./code:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dc_fpm
      - dc_postgres
    restart: unless-stopped

  fpm:
    build: .
    volumes:
        - ./code:/var/www/html
    restart: unless-stopped    

  postgres:
    image: postgres
    env_file: ./.env  
    restart: unless-stopped
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
